Puhl/jobhost dashboard
jguzdv/NuGet-Packages pull request #83
Opened 2024-03-06 15:33 UTC by MarcusLun

2024-03-07 10:57 UTC, glatzert requested changes

2024-03-07 10:57 UTC, glatzert commented on libraries/JGUZDV.JobHost.Dashboard.Blazor/JobTable.razor
> +    <table class="table">
Responsiveness?

2024-03-07 10:57 UTC, glatzert commented on libraries/JGUZDV.JobHost.Dashboard.Blazor/README.md
> +see JGUZDV.JobHost.Dashboard
Hier sollte ebenfalls eine kurze Readme mit Link auf die gesamte Readme liegen.

2024-03-07 10:57 UTC, glatzert commented on libraries/JGUZDV.JobHost.Dashboard.Blazor/_Imports.razor
> +﻿@using Microsoft.AspNetCore.Components.Web
Evtl JGUZDV... ergänzen, um die razor-Dateien mit weniger FullQualified Names zu beladen - fördert die Lesbarkeit

2024-03-07 10:57 UTC, glatzert commented on libraries/JGUZDV.JobHost.Dashboard.Blazor/DashboardState.cs
> +                     ValueExpiry = TimeSpan.FromSeconds(15)
Expiry Konfigurierbar?

2024-03-07 10:57 UTC, glatzert commented on libraries/JGUZDV.JobHost.Dashboard/samples/JGUZDV.JobHost.Dashboard.Sample/JGUZDV.JobHost.Dashboard.Sample.Client/Layout/MainLayout.razor
> +            <a href="https://learn.microsoft.com/aspnet/core/" target="_blank">About</a>
Reduzieren auf das eigentliche Beispiel

2024-03-07 10:57 UTC, glatzert commented on libraries/JGUZDV.JobHost.Dashboard/samples/JGUZDV.JobHost.Dashboard.Sample/JGUZDV.JobHost.Dashboard.Sample.Client/Layout/NavMenu.razor
> +                <span class="bi bi-plus-square-fill-nav-menu" aria-hidden="true"></span> Counter
Reduzieren auf das eigentliche Beispiel

2024-03-07 10:57 UTC, glatzert commented on libraries/JGUZDV.JobHost.Dashboard/samples/JGUZDV.JobHost.Dashboard.Sample/JGUZDV.JobHost.Dashboard.Sample.Client/Layout/NavMenu.razor
> +                <span class="bi bi-list-nested-nav-menu" aria-hidden="true"></span> Weather
Reduzieren auf das eigentliche Beispiel

2024-03-07 10:57 UTC, glatzert commented on libraries/JGUZDV.JobHost.Dashboard/samples/JGUZDV.JobHost.Dashboard.Sample/JGUZDV.JobHost.Dashboard.Sample.Client/Pages/Counter.razor
> +﻿@page "/counter"
Reduzieren auf das eigentliche Beispiel

2024-03-07 10:57 UTC, glatzert commented on libraries/JGUZDV.JobHost.Dashboard/src/JGUZDV.JobHost.Dashboard.csproj
> +  </PropertyGroup>
Unzureichende Properties für Nuget-Pakete

2024-03-07 10:57 UTC, glatzert commented on libraries/JGUZDV.JobHost.Dashboard/src/Model/Job.cs
> +        public bool ShouldExecute { get; set; }
Namingvorschlag: IsAdHocExecutionRequested

2024-03-07 10:57 UTC, glatzert commented on libraries/JGUZDV.JobHost.Dashboard/src/README.md
> +see JGUZDV.Jobhost
Kurze Beschreibung, link zur vollen Doku

2024-03-07 10:57 UTC, glatzert commented on libraries/JGUZDV.JobHost.Dashboard/src/Services/ApiClient.cs
> +            return _httpClient.PostAsync(Routes.ExecuteNow(jobId), null);
Fehlerbehandlung?

2024-03-07 10:57 UTC, glatzert commented on libraries/JGUZDV.JobHost.Dashboard/src/Services/ApiClient.cs
> +            return await _httpClient.GetFromJsonAsync<JobCollection>(Routes.GetJobs) ?? new JobCollection {
Fehlerbehandlung?

2024-03-07 10:57 UTC, glatzert commented on libraries/JGUZDV.JobHost.Database/src/JGUZDV.JobHost.Database.csproj
> +  </PropertyGroup>
Unzureichende Properties für Nuget-Paket

2024-03-07 10:57 UTC, glatzert commented on libraries/JGUZDV.JobHost.Database/src/JGUZDV.JobHost.Database.csproj
Projektnamingvorschlag:
JGUZDV.JobHost.Dashboard.EntityFramework
(aligned mit anderen Tools)

2024-03-07 10:57 UTC, glatzert commented on libraries/JGUZDV.JobHost/src/RegisterHost.cs
RegisterHost, RegisterJob, MetaJob und diese hier hätte ich gerne noch erklärt - die sind mir grade undurchsichtig

2024-03-07 10:57 UTC, glatzert commented on libraries/JGUZDV.JobHost/src/RegisterHost.cs
> +            _dbContext = dbContext;
Hier sollte mEn ein Interface auftauchen und nicht die Storage-Implementierung

2024-03-07 10:57 UTC, glatzert commented on libraries/JGUZDV.JobHost/src/RegisterJob.cs
> +        public async Task Execute(Host host, IScheduler scheduler, JobHostContext dbContext)
Hier sollte ein Storage oder Dashboard-Interface auftauchen - nicht die konkrete implementierung

2024-03-07 11:58 UTC, MarcusLun commented on libraries/JGUZDV.JobHost.Dashboard.Blazor/Extensions/ServiceCollectionExtensions.cs
> +            services.AddClientStoreWithNullStorage();
ja

2024-03-07 12:03 UTC, MarcusLun commented on libraries/JGUZDV.JobHost.Dashboard.Blazor/JobTable.razor
> +    <table class="table">
Ja

2024-03-11 11:00 UTC, glatzert requested changes

2024-03-13 14:35 UTC, glatzert requested changes

2024-03-13 14:35 UTC, glatzert commented on libraries/JGUZDV.JobHost.Database/src/JobHostContextReporter.cs
> +            var job = await dbContext.Jobs.FirstAsync(x => x.Name == name && x.Host!.Name == host);
Gute Möglichkeit für `dbContext.Jobs.Update()` - der aktuelle Zustand ist uns ja eigentlich "egal"

2024-03-13 14:35 UTC, glatzert commented on libraries/JGUZDV.JobHost.Database/src/JobHostContextReporter.cs
> +        public async Task<List<Abstractions.Model.Job>> GetPendingJobs()
Ich würde "ShouldExecute" als "AdHocExecutionRequestedAt" speichern - damit brauchst du zu keinem Zeitpunkt das "ShouldExecute" resetten

2024-03-18 11:40 UTC, glatzert requested changes

2024-03-18 11:40 UTC, glatzert commented on libraries/JGUZDV.JobHost.Dashboard.Blazor/JobTable.razor
> +    protected override async Task OnParametersSetAsync()
Leere Methode

2024-03-18 11:40 UTC, glatzert commented on libraries/JGUZDV.JobHost.Dashboard.Blazor/JobTable.razor
> +        await state.ExecuteNow(job.Id);
Wird dieser "forwarder" benötigt?

2024-03-18 11:40 UTC, glatzert commented on libraries/JGUZDV.JobHost.Dashboard.EntityFrameworkCore/src/DatabaseService.cs
> +            var context = await _dbContextFactory.CreateDbContextAsync();
using?

2024-03-18 11:40 UTC, glatzert commented on libraries/JGUZDV.JobHost.Dashboard.EntityFrameworkCore/src/DatabaseService.cs
> +            var context = await _dbContextFactory.CreateDbContextAsync(ct);
using?

2024-03-18 11:40 UTC, glatzert commented on libraries/JGUZDV.JobHost.Dashboard.EntityFrameworkCore/src/Entities/Job.cs
> +        public DateTimeOffset? ShouldExecuteAt { get; set; }
ShouldExecute finde ich immer noch ungünstig benannt für den "ExecuteNow" oder "Ad-Hoc execution" aufruf

2024-03-18 11:40 UTC, glatzert commented on libraries/JGUZDV.JobHost.Dashboard.EntityFrameworkCore/src/JobHostContextReporter.cs
> +                        LastResult = "",
ist null unangemessen für "noch nie"?

2024-03-18 11:40 UTC, glatzert commented on libraries/JGUZDV.JobHost.Dashboard.EntityFrameworkCore/src/JobHostContextReporter.cs
> +                        NextExecutionAt = item.NextExecutionAt,
Könnte ebenfalls "nie" sein, wenn der Job ohne Schedule registriert wird (kann sein, dass das noch nicht geht)

2024-03-18 11:40 UTC, glatzert commented on libraries/JGUZDV.JobHost.Dashboard.EntityFrameworkCore/src/JobHostContextReporter.cs
> +                job.LastResult = "success";
-> const string JobResults.Success = "success"
-> const string JobResult.Error = "error"

2024-03-18 11:40 UTC, glatzert commented on libraries/JGUZDV.JobHost.Dashboard/samples/JGUZDV.JobHost.Dashboard.Sample/JGUZDV.JobHost.Dashboard.Sample.Client/Program.cs
> +builder.Services.AddTransient<IDashboardService, ApiClient>(x =>
`AddHttpClient<>()`

2024-03-18 11:40 UTC, glatzert commented on libraries/JGUZDV.JobHost/src/JobListener.cs
> +            while(true)
Die Bedingung des if () könnte auch die Schleifen-Bedingung sein und dann das return schlicht ausßerhalb der loop liegen.

2024-03-18 11:40 UTC, glatzert commented on libraries/JGUZDV.JobHost/src/JobListener.cs
> +                exception = exception.InnerException;
Parameterzuweisung - manchmal ist das "frowned upon" ...

2024-03-18 11:40 UTC, glatzert commented on libraries/JGUZDV.JobHost/src/RegisterHost.cs
> +    internal class RegisterHost : IJob
Ich dachte das solle ein IHostedService werden?

2024-04-04 15:35 UTC, aaron-puhl submitted a review, later dismissed

2024-04-05 13:18 UTC, glatzert requested changes

2024-04-05 13:18 UTC, glatzert commented on .github/workflows/JGUZDV.JobHost.Dashboard.Api.yml
> +      run-tests: false
Nur für Ausnahmefälle

2024-04-05 13:18 UTC, glatzert commented on .github/workflows/JGUZDV.JobHost.Dashboard.Blazor.yml
> +      run-tests: false
Nur für Ausnahmefälle

2024-04-05 13:18 UTC, glatzert commented on .github/workflows/JGUZDV.JobHost.Dashboard.EntityFrameworkCore.yml
> +      run-tests: false
Nur für Ausnahmefälle

2024-04-05 13:18 UTC, glatzert commented on .github/workflows/JGUZDV.JobHost.Dashboard.Shared.yml
> +      run-tests: false
Nur für Ausnahmefälle

2024-04-05 13:18 UTC, glatzert commented on .github/workflows/JGUZDV.JobHost.Shared.yml
> +      run-tests: false
Nur für Ausnahmefälle

2024-04-05 13:18 UTC, glatzert commented on .github/workflows/JGUZDV.JobHost.Dashboard.EntityFrameworkCore.yml
> +      run-tests: false
.. der vermutlich genau hier ist

2024-04-16 12:25 UTC, glatzert approved these changes

2024-04-16 12:45 UTC, glatzert approved these changes

2024-04-16 12:47 UTC, merged