Puhl/action button
jguzdv/NuGet-Packages pull request #87
Opened 2024-03-18 13:11 UTC by aaron-puhl

2024-03-21 08:54 UTC, glatzert requested changes

2024-03-21 08:54 UTC, glatzert commented on libraries/JGUZDV.Blazor.Components/src/Extensions/BrowserEventExtensions.cs
> +        /// <param name="e"></param>
Angegebene `<param>` sollten auch definiert sein.

2024-03-21 08:54 UTC, glatzert commented on libraries/JGUZDV.Blazor.Components/src/Inputs/ActionButton.razor
> +    private async Task HandleClick()
Code-Duplikat mit Zeile 48.
Code vereinheitlichen

2024-03-21 08:54 UTC, glatzert commented on libraries/JGUZDV.Blazor.Components/src/Inputs/ActionButton.razor
> +        _isRunning = true;
Reicht uns der bool als Semaphore hier?

2024-03-21 08:54 UTC, glatzert commented on libraries/JGUZDV.Blazor.Components/src/Inputs/ActionButton.razor
> +        _isRunning = true;
Ah - du lässt mehrfach ausführen zu ..

2024-03-21 08:54 UTC, glatzert commented on libraries/JGUZDV.Blazor.Components/src/Inputs/ActionButton.razor
> +        class="@AdditionalAttributes?.GetValueOrDefault("class") @(_isRunning  ? "position-relative" : "")"
Benötigt das ein position-relative, oder könnte man das auch über ::after abbilden?

2024-03-21 09:12 UTC, aaron-puhl commented on libraries/JGUZDV.Blazor.Components/src/Inputs/ActionButton.razor
> +        _isRunning = true;
Jein, der button wird mit dem nächsten Renderzyklus disabled.

2024-03-21 09:14 UTC, aaron-puhl commented on libraries/JGUZDV.Blazor.Components/src/Inputs/ActionButton.razor
> +        class="@AdditionalAttributes?.GetValueOrDefault("class") @(_isRunning  ? "position-relative" : "")"
::after fügt nur etwas hinzu oder? das relative ist ja dafür da damit die absolute Positionierung funktioniert.

2024-03-21 09:16 UTC, aaron-puhl commented on libraries/JGUZDV.Blazor.Components/src/Inputs/ActionButton.razor
> +        _isRunning = true;
Aber wenn wir schon drüber reden, hatte drüber nachgedacht das als Parameter und Task abzubilden

2024-04-30 10:28 UTC, aaron-puhl commented on libraries/JGUZDV.Blazor.Components/src/Inputs/ActionButton.razor
> +        _isRunning = true;
@glatzert  ping

2025-02-14 10:20 UTC, glatzert commented
@aaron-puhl was waren nochmal die Design-Ziele hier?
Der Button ist ähnlich zu den Editor-Buttons, richtig?
Können wir da ebenfalls Task _oder_ CascadingParameter annehmen?

2026-04-14 14:57 UTC, closed without merging